[alias]
prisma = "run -p prisma-cli --bin prisma --"
prisma-sync = "run -p prisma-cli --bin sync --"

# temprary until https://github.com/RustCrypto/block-ciphers/pull/380
[target.'cfg(target_arch = "aarch64")']
rustflags = ["--cfg", "aes_armv8"]
